name: Check Markdown Links

on:
  push:
    branches:
      - main
      - enhancements
    paths:
      - '**.md'
      - '.github/workflows/link-checker.yml'
  pull_request:
    paths:
      - '**.md'
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown-link-check-config.json'
          folder-path: '.'
          file-extension: '.md'

      - name: Create issue if links are broken
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔗 Broken links detected in documentation';
            const body = `
            ## Broken Links Detected
            
            The automated link checker has found broken links in the documentation.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            
            Please review the workflow logs and fix the broken links.
            
            ### Next Steps
            1. Check the workflow logs for specific broken links
            2. Update or remove broken links
            3. Re-run the workflow to verify fixes
            
            ---
            *This issue was automatically created by the link checker workflow.*
            `;
            
            // Check if an issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'broken-links'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['documentation', 'broken-links', 'automated']
              });
            }
