name: Markdown Lint

on:
  pull_request:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: ".markdownlint.json"
          ignore_files: "node_modules/"
